// 메인페이지
// 리액트의 app.js 파일과 같음
import Head from 'next/head';
import Main from '@/components/page/main';
import ArrowUp from '@/components/common/arrowUp';
import Footer from '@/components/layout/footer';
import Skills from '@/components/page/skills';
import About from '@/components/page/about';
import Projects from '@/components/page/projects';
import { useAppContext } from './context/AppContext';

export default function Home(): JSX.Element {
  const { isLightMode } = useAppContext();

  return (
    <>
      <Head>
        <title>Soeuns First portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div id={isLightMode ? 'light' : 'dark'}>
        <main className="main">
          <Main />
          <ArrowUp />
        </main>
        <article className="skillsWrap">
          <Skills />
        </article>
        <article className="projectWrap">
          <Projects />
        </article>
        <article className="aboutWrap">
          <About />
        </article>
        <footer className="footer">
          <Footer />
        </footer>
      </div>
    </>
  );
}
