// 메인페이지
// 리액트의 app.js 파일과 같음
import Head from 'next/head';
import styles from '@/styles/index.module.css';
import Main from '@/components/page/main';
import Skills from '@/components/page/skills';

export default function Home(): JSX.Element {
  return (
    <>
      <Head>
        <title>Soeuns First portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <Main />
      </main>
      <article className={styles.article}>
        <Skills />
      </article>
    </>
  );
}
