// 메인페이지
// 리액트의 app.js 파일과 같음
import Head from 'next/head';
import styles from '@/styles/index.module.css';
import Main from '@/components/page/main';
import ArrowUp from '@/components/common/arrowUp';
import Footer from '@/components/layout/footer';
import Skills from '@/components/page/skills';
import About from '@/components/page/about';
import Projects from '@/components/page/projects';

export default function Home(): JSX.Element {
  return (
    <>
      <Head>
        <title>Soeuns First portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <Main />
        <ArrowUp />
      </main>
      <article className={styles.skillsWrap}>
        <Skills />
      </article>
      <article className={styles.projectWrap}>
        <Projects />
      </article>
      <article className={styles.aboutWrap}>
        <About />
      </article>
      <Footer />
    </>
  );
}
